# -*- coding: utf-8 -*-
"""
Labour Force Survey analysis codebook
"""

dictionary = {}

dictionary['var_string'] = {#
            # Year turned 18 - year_age18_5yrband_agg_doctoronly
            'year_age18_5yrband_agg_doctoronly_12: Pre-1970':'Year turned 18: Pre-1970',
            'year_age18_5yrband_agg_doctoronly_13: 1970-1975':'Year turned 18: 1970-1974',
            'year_age18_5yrband_agg_doctoronly_14: 1975-1980':'Year turned 18: 1975-1979',
            'year_age18_5yrband_agg_doctoronly_15: 1980-1985':'Year turned 18: 1980-1984 (reference)', 
            'year_age18_5yrband_agg_doctoronly_16: 1985-1990':'Year turned 18: 1985-1989',
            'year_age18_5yrband_agg_doctoronly_17: 1990-1995':'Year turned 18: 1990-1994',
            'year_age18_5yrband_agg_doctoronly_18: 1995-2000':'Year turned 18: 1995-1999',
            'year_age18_5yrband_agg_doctoronly_19: 2000-2005':'Year turned 18: 2000-2004', 
            'year_age18_5yrband_agg_doctoronly_20: 2005-2010':'Year turned 18: 2005-2009',
            'year_age18_5yrband_agg_doctoronly_21: Post-2010':'Year turned 18: Post-2010',
            
            # Year turned 18 - year_age18_5yrband_agg_doctorORdegree
            'year_age18_5yrband_agg_doctorORdegree_11: Pre-1965':'Year turned 18: Pre-1965', 
            'year_age18_5yrband_agg_doctorORdegree_12: 1965-1970':'Year turned 18: 1965-1969',
            'year_age18_5yrband_agg_doctorORdegree_13: 1970-1975':'Year turned 18: 1970-1974',
            'year_age18_5yrband_agg_doctorORdegree_14: 1975-1980':'Year turned 18: 1975-1979', 
            'year_age18_5yrband_agg_doctorORdegree_15: 1980-1985':'Year turned 18: 1980-1984 (reference)', 
            'year_age18_5yrband_agg_doctorORdegree_16: 1985-1990':'Year turned 18: 1985-1989', 
            'year_age18_5yrband_agg_doctorORdegree_17: 1990-1995':'Year turned 18: 1990-1994', 
            'year_age18_5yrband_agg_doctorORdegree_18: 1995-2000':'Year turned 18: 1995-1999',
            'year_age18_5yrband_agg_doctorORdegree_19: 2000-2005':'Year turned 18: 2000-2004',
            'year_age18_5yrband_agg_doctorORdegree_20: 2005-2010':'Year turned 18: 2005-2009',
            'year_age18_5yrband_agg_doctorORdegree_21: Post-2010':'Year turned 18: Post-2010',
            
            # Sex - SEX
            'SEX_1':'Sex: Male', 
            'SEX_2':'Sex: Female',
            
            # Country of birth - CRY12
            'CRY12_-9':'Country of birth: Missing',
            'CRY12_356':'Country of birth: India',
            'CRY12_372':'Country of birth: Republic of Ireland',
            'CRY12_586':'Country of birth: Pakistan',
            'CRY12_616':'Country of birth: Poland',
            'CRY12_921':'Country of birth: England (reference)',
            'CRY12_922':'Country of birth: Northern Ireland',
            'CRY12_923':'Country of birth: Scotland',
            'CRY12_924':'Country of birth: Wales',
            'CRY12_926':'Country of birth: UK (unspecified)',
            'CRY12_997':'Country of birth: Any other country', 
            
            # Ethnic group - ETHUKEUL
            'ETHUKEUL_-8':'Ethnic group: Missing', 
            'ETHUKEUL_1':'Ethnic group: White ethnic groups (reference)',
            'ETHUKEUL_2':'Ethnic group: Mixed/Multiple ethnic groups',
            'ETHUKEUL_3':'Ethnic group: Asian/Asian British ethnic groups, Indian',
            'ETHUKEUL_4':'Ethnic group: Asian/Asian British ethnic groups, Pakistani',
            'ETHUKEUL_5':'Ethnic group: Asian/Asian British ethnic groups, Bangladeshi', 
            'ETHUKEUL_6':'Ethnic group: Asian/Asian British ethnic groups, Chinese',
            'ETHUKEUL_7':'Ethnic group: Asian/Asian British ethnic groups, Any other', 
            'ETHUKEUL_8':'Ethnic group: Black/Black British ethnic groups', 
            'ETHUKEUL_9':'Ethnic group: Any other ethnic groups',
            
            # Doctor as parent - Flag_MainEarner_221_Doctor
            'Flag_MainEarner_221_Doctor_NaN':'Household main earner was a doctor: No (reference)', 
            'Flag_MainEarner_221_Doctor_1.0':'Household main earner was a doctor: Yes', 
             
            # Individual occupations - SOC_occupation_familyback_separatedoctor
            'SOC_occupation_familyback_separatedoctor_2211.0':'Household main earner occupation: Doctor (reference)',
            'SOC_occupation_familyback_separatedoctor_-9.0':'Household main earner occupation: Does not apply', 
            'SOC_occupation_familyback_separatedoctor_-8.0':'Household main earner occupation: Do not know', 
            'SOC_occupation_familyback_separatedoctor_111.0':'Household main earner occupation: 111',
            'SOC_occupation_familyback_separatedoctor_112.0':'Household main earner occupation: 112',
            'SOC_occupation_familyback_separatedoctor_113.0':'Household main earner occupation: 113',
            'SOC_occupation_familyback_separatedoctor_114.0':'Household main earner occupation: 114',
            'SOC_occupation_familyback_separatedoctor_115.0':'Household main earner occupation: 115', 
            'SOC_occupation_familyback_separatedoctor_116.0':'Household main earner occupation: 116',
            'SOC_occupation_familyback_separatedoctor_117.0':'Household main earner occupation: 117',
            'SOC_occupation_familyback_separatedoctor_118.0':'Household main earner occupation: 118',
            'SOC_occupation_familyback_separatedoctor_119.0':'Household main earner occupation: 119', 
            'SOC_occupation_familyback_separatedoctor_121.0':'Household main earner occupation: 121',
            'SOC_occupation_familyback_separatedoctor_122.0':'Household main earner occupation: 122',
            'SOC_occupation_familyback_separatedoctor_123.0':'Household main earner occupation: 123',
            'SOC_occupation_familyback_separatedoctor_124.0':'Household main earner occupation: 124',
            'SOC_occupation_familyback_separatedoctor_125.0':'Household main earner occupation: 125',
            'SOC_occupation_familyback_separatedoctor_211.0':'Household main earner occupation: 211',
            'SOC_occupation_familyback_separatedoctor_212.0':'Household main earner occupation: 212',
            'SOC_occupation_familyback_separatedoctor_213.0':'Household main earner occupation: 213',
            'SOC_occupation_familyback_separatedoctor_214.0':'Household main earner occupation: 214',
            'SOC_occupation_familyback_separatedoctor_215.0':'Household main earner occupation: 215',
            'SOC_occupation_familyback_separatedoctor_216.0':'Household main earner occupation: 216',
            'SOC_occupation_familyback_separatedoctor_221.0':'Household main earner occupation: 221 (excluding doctor)',
            'SOC_occupation_familyback_separatedoctor_222.0':'Household main earner occupation: 222',
            'SOC_occupation_familyback_separatedoctor_223.0':'Household main earner occupation: 223',
            'SOC_occupation_familyback_separatedoctor_224.0':'Household main earner occupation: 224',
            'SOC_occupation_familyback_separatedoctor_225.0':'Household main earner occupation: 225', 
            'SOC_occupation_familyback_separatedoctor_231.0':'Household main earner occupation: 231',
            'SOC_occupation_familyback_separatedoctor_232.0':'Household main earner occupation: 232',
            'SOC_occupation_familyback_separatedoctor_241.0':'Household main earner occupation: 241',
            'SOC_occupation_familyback_separatedoctor_242.0':'Household main earner occupation: 242',
            'SOC_occupation_familyback_separatedoctor_243.0':'Household main earner occupation: 243', 
            'SOC_occupation_familyback_separatedoctor_244.0':'Household main earner occupation: 244', 
            'SOC_occupation_familyback_separatedoctor_245.0':'Household main earner occupation: 245',
            'SOC_occupation_familyback_separatedoctor_246.0':'Household main earner occupation: 246',
            'SOC_occupation_familyback_separatedoctor_247.0':'Household main earner occupation: 247',
            'SOC_occupation_familyback_separatedoctor_248.0':'Household main earner occupation: 248',
            'SOC_occupation_familyback_separatedoctor_249.0':'Household main earner occupation: 249',
            'SOC_occupation_familyback_separatedoctor_311.0':'Household main earner occupation: 311',
            'SOC_occupation_familyback_separatedoctor_312.0':'Household main earner occupation: 312',
            'SOC_occupation_familyback_separatedoctor_313.0':'Household main earner occupation: 313', 
            'SOC_occupation_familyback_separatedoctor_321.0':'Household main earner occupation: 321', 
            'SOC_occupation_familyback_separatedoctor_322.0':'Household main earner occupation: 322', 
            'SOC_occupation_familyback_separatedoctor_323.0':'Household main earner occupation: 323', 
            'SOC_occupation_familyback_separatedoctor_324.0':'Household main earner occupation: 324',
            'SOC_occupation_familyback_separatedoctor_331.0':'Household main earner occupation: 331',
            'SOC_occupation_familyback_separatedoctor_341.0':'Household main earner occupation: 341',
            'SOC_occupation_familyback_separatedoctor_342.0':'Household main earner occupation: 342', 
            'SOC_occupation_familyback_separatedoctor_343.0':'Household main earner occupation: 343',
            'SOC_occupation_familyback_separatedoctor_344.0':'Household main earner occupation: 344',
            'SOC_occupation_familyback_separatedoctor_351.0':'Household main earner occupation: 351',
            'SOC_occupation_familyback_separatedoctor_352.0':'Household main earner occupation: 352',
            'SOC_occupation_familyback_separatedoctor_353.0':'Household main earner occupation: 353', 
            'SOC_occupation_familyback_separatedoctor_354.0':'Household main earner occupation: 354', 
            'SOC_occupation_familyback_separatedoctor_355.0':'Household main earner occupation: 355', 
            'SOC_occupation_familyback_separatedoctor_356.0':'Household main earner occupation: 356', 
            'SOC_occupation_familyback_separatedoctor_357.0':'Household main earner occupation: 357', 
            'SOC_occupation_familyback_separatedoctor_358.0':'Household main earner occupation: 358', 
            'SOC_occupation_familyback_separatedoctor_411.0':'Household main earner occupation: 411', 
            'SOC_occupation_familyback_separatedoctor_412.0':'Household main earner occupation: 412', 
            'SOC_occupation_familyback_separatedoctor_413.0':'Household main earner occupation: 413',
            'SOC_occupation_familyback_separatedoctor_414.0':'Household main earner occupation: 414',
            'SOC_occupation_familyback_separatedoctor_415.0':'Household main earner occupation: 415',
            'SOC_occupation_familyback_separatedoctor_416.0':'Household main earner occupation: 416',
            'SOC_occupation_familyback_separatedoctor_421.0':'Household main earner occupation: 421',
            'SOC_occupation_familyback_separatedoctor_511.0':'Household main earner occupation: 511',
            'SOC_occupation_familyback_separatedoctor_521.0':'Household main earner occupation: 521',
            'SOC_occupation_familyback_separatedoctor_522.0':'Household main earner occupation: 522',
            'SOC_occupation_familyback_separatedoctor_523.0':'Household main earner occupation: 523',
            'SOC_occupation_familyback_separatedoctor_524.0':'Household main earner occupation: 524',
            'SOC_occupation_familyback_separatedoctor_525.0':'Household main earner occupation: 525',
            'SOC_occupation_familyback_separatedoctor_531.0':'Household main earner occupation: 531',
            'SOC_occupation_familyback_separatedoctor_532.0':'Household main earner occupation: 532',
            'SOC_occupation_familyback_separatedoctor_533.0':'Household main earner occupation: 533',
            'SOC_occupation_familyback_separatedoctor_541.0':'Household main earner occupation: 541',
            'SOC_occupation_familyback_separatedoctor_542.0':'Household main earner occupation: 542',
            'SOC_occupation_familyback_separatedoctor_543.0':'Household main earner occupation: 543',
            'SOC_occupation_familyback_separatedoctor_544.0':'Household main earner occupation: 544',
            'SOC_occupation_familyback_separatedoctor_611.0':'Household main earner occupation: 611',
            'SOC_occupation_familyback_separatedoctor_612.0':'Household main earner occupation: 612',
            'SOC_occupation_familyback_separatedoctor_613.0':'Household main earner occupation: 613',
            'SOC_occupation_familyback_separatedoctor_614.0':'Household main earner occupation: 614',
            'SOC_occupation_familyback_separatedoctor_621.0':'Household main earner occupation: 621',
            'SOC_occupation_familyback_separatedoctor_622.0':'Household main earner occupation: 622', 
            'SOC_occupation_familyback_separatedoctor_623.0':'Household main earner occupation: 623', 
            'SOC_occupation_familyback_separatedoctor_624.0':'Household main earner occupation: 624', 
            'SOC_occupation_familyback_separatedoctor_625.0':'Household main earner occupation: 625', 
            'SOC_occupation_familyback_separatedoctor_631.0':'Household main earner occupation: 631',
            'SOC_occupation_familyback_separatedoctor_643.0':'Household main earner occupation: 643',
            'SOC_occupation_familyback_separatedoctor_711.0':'Household main earner occupation: 711',
            'SOC_occupation_familyback_separatedoctor_712.0':'Household main earner occupation: 712',
            'SOC_occupation_familyback_separatedoctor_713.0':'Household main earner occupation: 713',
            'SOC_occupation_familyback_separatedoctor_721.0':'Household main earner occupation: 721',
            'SOC_occupation_familyback_separatedoctor_722.0':'Household main earner occupation: 722',
            'SOC_occupation_familyback_separatedoctor_811.0':'Household main earner occupation: 811',
            'SOC_occupation_familyback_separatedoctor_812.0':'Household main earner occupation: 812', 
            'SOC_occupation_familyback_separatedoctor_813.0':'Household main earner occupation: 813',
            'SOC_occupation_familyback_separatedoctor_814.0':'Household main earner occupation: 814',
            'SOC_occupation_familyback_separatedoctor_815.0':'Household main earner occupation: 815',
            'SOC_occupation_familyback_separatedoctor_816.0':'Household main earner occupation: 816',
            'SOC_occupation_familyback_separatedoctor_821.0':'Household main earner occupation: 821',
            'SOC_occupation_familyback_separatedoctor_822.0':'Household main earner occupation: 822',
            'SOC_occupation_familyback_separatedoctor_823.0':'Household main earner occupation: 823',
            'SOC_occupation_familyback_separatedoctor_911.0':'Household main earner occupation: 911',
            'SOC_occupation_familyback_separatedoctor_912.0':'Household main earner occupation: 912',
            'SOC_occupation_familyback_separatedoctor_913.0':'Household main earner occupation: 913',
            'SOC_occupation_familyback_separatedoctor_921.0':'Household main earner occupation: 921',
            'SOC_occupation_familyback_separatedoctor_922.0':'Household main earner occupation: 922',
            'SOC_occupation_familyback_separatedoctor_923.0':'Household main earner occupation: 923',
            'SOC_occupation_familyback_separatedoctor_924.0':'Household main earner occupation: 924',
            'SOC_occupation_familyback_separatedoctor_925.0':'Household main earner occupation: 925',
            'SOC_occupation_familyback_separatedoctor_926.0':'Household main earner occupation: 926',
            'SOC_occupation_familyback_separatedoctor_927.0':'Household main earner occupation: 927',
            'SOC_occupation_familyback_separatedoctor_999.0':'Household main earner occupation: 999', 
            
            # Socio-economic background
            # DOCTOR AS PART OF WIDER CATEGORY
            # NS-SEC 9-cat       
            'nssec_familybackground_9cat_1.1':'Socio-economic background: NS-SEC 1.1 (reference)',
            'nssec_familybackground_9cat_1.2':'Socio-economic background: NS-SEC 1.2',
            'nssec_familybackground_9cat_2':'Socio-economic background: NS-SEC 2',
            'nssec_familybackground_9cat_3':'Socio-economic background: NS-SEC 3',
            'nssec_familybackground_9cat_4':'Socio-economic background: NS-SEC 4',
            'nssec_familybackground_9cat_5':'Socio-economic background: NS-SEC 5',
            'nssec_familybackground_9cat_6':'Socio-economic background: NS-SEC 6',
            'nssec_familybackground_9cat_7':'Socio-economic background: NS-SEC 7',
            'nssec_familybackground_9cat_8':'Socio-economic background: NS-SEC 8',
            'nssec_familybackground_9cat_Not living with family':'Socio-economic background: Not living with family',
            
            # NS-SEC 8-cat
            'nssec_familybackground_8cat_1':'Socio-economic background: NS-SEC 1 (reference)',
            'nssec_familybackground_8cat_2':'Socio-economic background: NS-SEC 2',
            'nssec_familybackground_8cat_3':'Socio-economic background: NS-SEC 3', 
            'nssec_familybackground_8cat_4':'Socio-economic background: NS-SEC 4',
            'nssec_familybackground_8cat_5':'Socio-economic background: NS-SEC 5',
            'nssec_familybackground_8cat_6':'Socio-economic background: NS-SEC 6',
            'nssec_familybackground_8cat_7':'Socio-economic background: NS-SEC 7',
            'nssec_familybackground_8cat_8':'Socio-economic background: NS-SEC 8',
            'nssec_familybackground_8cat_Not living with family':'Socio-economic background: Not living with family',
            
            # NS-SEC 5-cat
            'nssec_familybackground_5cat_1-2':'Socio-economic background: NS-SEC 1-2 (reference)',
            'nssec_familybackground_5cat_3':'Socio-economic background: NS-SEC 3',
            'nssec_familybackground_5cat_4':'Socio-economic background: NS-SEC 4',
            'nssec_familybackground_5cat_5':'Socio-economic background: NS-SEC 5',
            'nssec_familybackground_5cat_6-7':'Socio-economic background: NS-SEC 6-7', 
            'nssec_familybackground_5cat_8':'Socio-economic background: NS-SEC 8',
            'nssec_familybackground_5cat_Not living with family':'Socio-economic background: Not living with family',
            
            # NS-SEC 4-cat
            'nssec_familybackground_4cat_1-2':'Socio-economic background: NS-SEC 1-2 (reference)',
            'nssec_familybackground_4cat_3-4':'Socio-economic background: NS-SEC 3-4',
            'nssec_familybackground_4cat_5-7':'Socio-economic background: NS-SEC 5-7',
            'nssec_familybackground_4cat_8':'Socio-economic background: NS-SEC 8',
            'nssec_familybackground_4cat_Not living with family':'Socio-economic background: Not living with family',
            
            # NS-SEC 3-cat 
            'nssec_familybackground_3cat_1-2':'Socio-economic background: NS-SEC 1-2 (reference)',
            'nssec_familybackground_3cat_3-4':'Socio-economic background: NS-SEC 3-4',
            'nssec_familybackground_3cat_5-8':'Socio-economic background: NS-SEC 5-8',
            
            
            # DOCTOR AS SEPARATE CATEGORY
            # NS-SEC 9-cat       
            'nssec_familybackground_separatedoctor_9cat_1.1':'Socio-economic background: NS-SEC 1.1',
            'nssec_familybackground_separatedoctor_9cat_Doctor':'Socio-economic background: NS-SEC 1.2. Doctor (reference)',
            'nssec_familybackground_separatedoctor_9cat_1.2':'Socio-economic background: NS-SEC 1.2. All other',
            'nssec_familybackground_separatedoctor_9cat_2':'Socio-economic background: NS-SEC 2',
            'nssec_familybackground_separatedoctor_9cat_3':'Socio-economic background: NS-SEC 3',
            'nssec_familybackground_separatedoctor_9cat_4':'Socio-economic background: NS-SEC 4',
            'nssec_familybackground_separatedoctor_9cat_5':'Socio-economic background: NS-SEC 5',
            'nssec_familybackground_separatedoctor_9cat_6':'Socio-economic background: NS-SEC 6',
            'nssec_familybackground_separatedoctor_9cat_7':'Socio-economic background: NS-SEC 7',
            'nssec_familybackground_separatedoctor_9cat_8':'Socio-economic background: NS-SEC 8',
            'nssec_familybackground_separatedoctor_9cat_Not living with family':'Socio-economic background: Not living with family',
            
            # NS-SEC 8-cat
            'nssec_familybackground_separatedoctor_8cat_Doctor':'Socio-economic background: NS-SEC 1. Doctor (reference)',
            'nssec_familybackground_separatedoctor_8cat_1':'Socio-economic background: NS-SEC 1. All other',
            'nssec_familybackground_separatedoctor_8cat_2':'Socio-economic background: NS-SEC 2',
            'nssec_familybackground_separatedoctor_8cat_3':'Socio-economic background: NS-SEC 3', 
            'nssec_familybackground_separatedoctor_8cat_4':'Socio-economic background: NS-SEC 4',
            'nssec_familybackground_separatedoctor_8cat_5':'Socio-economic background: NS-SEC 5',
            'nssec_familybackground_separatedoctor_8cat_6':'Socio-economic background: NS-SEC 6',
            'nssec_familybackground_separatedoctor_8cat_7':'Socio-economic background: NS-SEC 7',
            'nssec_familybackground_separatedoctor_8cat_8':'Socio-economic background: NS-SEC 8',
            'nssec_familybackground_separatedoctor_8cat_Not living with family':'Socio-economic background: Not living with family',
            
            # NS-SEC 5-cat
            'nssec_familybackground_separatedoctor_5cat_Doctor':'Socio-economic background: NS-SEC 1-2. Doctor (reference)', 
            'nssec_familybackground_separatedoctor_5cat_1-2':'Socio-economic background: NS-SEC 1-2. All other',
            'nssec_familybackground_separatedoctor_5cat_3':'Socio-economic background: NS-SEC 3',
            'nssec_familybackground_separatedoctor_5cat_4':'Socio-economic background: NS-SEC 4',
            'nssec_familybackground_separatedoctor_5cat_5':'Socio-economic background: NS-SEC 5',
            'nssec_familybackground_separatedoctor_5cat_6-7':'Socio-economic background: NS-SEC 6-7', 
            'nssec_familybackground_separatedoctor_5cat_8':'Socio-economic background: NS-SEC 8',
            'nssec_familybackground_separatedoctor_5cat_Not living with family':'Socio-economic background: Not living with family',
            
            # NS-SEC 4-cat
            'nssec_familybackground_separatedoctor_4cat_Doctor':'Socio-economic background: NS-SEC 1-2. Doctor (reference)',
            'nssec_familybackground_separatedoctor_4cat_1-2':'Socio-economic background: NS-SEC 1-2. All other',
            'nssec_familybackground_separatedoctor_4cat_3-4':'Socio-economic background: NS-SEC 3-4',
            'nssec_familybackground_separatedoctor_4cat_5-7':'Socio-economic background: NS-SEC 5-7',
            'nssec_familybackground_separatedoctor_4cat_8':'Socio-economic background: NS-SEC 8',
            'nssec_familybackground_separatedoctor_4cat_Not living with family':'Socio-economic background: Not living with family',
            
            # NS-SEC 3-cat
            'nssec_familybackground_separatedoctor_3cat_Doctor':'Socio-economic background: NS-SEC 1-2. Doctor (reference)', 
            'nssec_familybackground_separatedoctor_3cat_1-2':'Socio-economic background: NS-SEC 1-2. All other',
            'nssec_familybackground_separatedoctor_3cat_3-4':'Socio-economic background: NS-SEC 3-4',
            'nssec_familybackground_separatedoctor_3cat_5-8':'Socio-economic background: NS-SEC 5-8',
            
            # Survey year
            'lfs_year_2014':'Survey year: 2014', 
            'lfs_year_2015':'Survey year: 2015', 
            'lfs_year_2016':'Survey year: 2016', 
            'lfs_year_2017':'Survey year: 2017', 
            'lfs_year_2018':'Survey year: 2018', 
            'lfs_year_2019':'Survey year: 2019',
            'lfs_year_2020':'Survey year: 2020', 
            'lfs_year_2021':'Survey year: 2021', 
            'lfs_year_2022':'Survey year: 2022', 
            'lfs_year_2023':'Survey year: 2023',
            
            }


# Short version, omitting variable name and shortening for space
dictionary['var_string_short'] = {
            # Year turned 18 - year_age18_5yrband_agg_doctoronly
            'year_age18_5yrband_agg_doctoronly_12: Pre-1970':'Pre-1970',
            'year_age18_5yrband_agg_doctoronly_13: 1970-1975':'1970-1974',
            'year_age18_5yrband_agg_doctoronly_14: 1975-1980':'1975-1979',
            'year_age18_5yrband_agg_doctoronly_15: 1980-1985':'1980-1984 (reference)', 
            'year_age18_5yrband_agg_doctoronly_16: 1985-1990':'1985-1989',
            'year_age18_5yrband_agg_doctoronly_17: 1990-1995':'1990-1994',
            'year_age18_5yrband_agg_doctoronly_18: 1995-2000':'1995-1999',
            'year_age18_5yrband_agg_doctoronly_19: 2000-2005':'2000-2004', 
            'year_age18_5yrband_agg_doctoronly_20: 2005-2010':'2005-2009',
            'year_age18_5yrband_agg_doctoronly_21: Post-2010':'Post-2010',
            
            # Year turned 18 - year_age18_5yrband_agg_doctorORdegree
            'year_age18_5yrband_agg_doctorORdegree_11: Pre-1965':'Pre-1965', 
            'year_age18_5yrband_agg_doctorORdegree_12: 1965-1970':'1965-1969',
            'year_age18_5yrband_agg_doctorORdegree_13: 1970-1975':'1970-1974',
            'year_age18_5yrband_agg_doctorORdegree_14: 1975-1980':'1975-1979', 
            'year_age18_5yrband_agg_doctorORdegree_15: 1980-1985':'1980-1984 (reference)', 
            'year_age18_5yrband_agg_doctorORdegree_16: 1985-1990':'1985-1979', 
            'year_age18_5yrband_agg_doctorORdegree_17: 1990-1995':'1990-1994', 
            'year_age18_5yrband_agg_doctorORdegree_18: 1995-2000':'1995-1999',
            'year_age18_5yrband_agg_doctorORdegree_19: 2000-2005':'2000-2004',
            'year_age18_5yrband_agg_doctorORdegree_20: 2005-2010':'2005-2009',
            'year_age18_5yrband_agg_doctorORdegree_21: Post-2010':'Post-2010',
            
            # Sex - SEX
            'SEX_1':'Male', 
            'SEX_2':'Female',
            
            # Country of birth - CRY12
            'CRY12_-9':'Missing',
            'CRY12_356':'India',
            'CRY12_372':'Republic of Ireland',
            'CRY12_586':'Pakistan',
            'CRY12_616':'Poland',
            'CRY12_921':'England (reference)',
            'CRY12_922':'Northern Ireland',
            'CRY12_923':'Scotland',
            'CRY12_924':'Wales',
            'CRY12_926':'UK (unspecified)',
            'CRY12_997':'Any other country', 
            
            # Ethnic group - ETHUKEUL
            'ETHUKEUL_-8':'Missing', 
            'ETHUKEUL_1':'White ethnic groups (reference)',
            'ETHUKEUL_2':'Mixed/Multiple ethnic groups',
            'ETHUKEUL_3':'Asian/Asian British ethnic groups, Indian',
            'ETHUKEUL_4':'Asian/Asian British ethnic groups, Pakistani',
            'ETHUKEUL_5':'Asian/Asian British ethnic groups, Bangladeshi', 
            'ETHUKEUL_6':'Asian/Asian British ethnic groups, Chinese',
            'ETHUKEUL_7':'Asian/Asian British ethnic groups, Any other', 
            'ETHUKEUL_8':'Black/Black British ethnic groups', 
            'ETHUKEUL_9':'Any other ethnic groups',
            
            # Doctor as parent - Flag_MainEarner_221_Doctor
            'Flag_MainEarner_221_Doctor_NaN':'No (reference)', 
            'Flag_MainEarner_221_Doctor_1.0':'Yes', 
             
            # Individual occupations - SOC_occupation_familyback_separatedoctor
            'SOC_occupation_familyback_separatedoctor_2211.0':'Medical practitioner (Doctor) (reference)',
            # 'SOC_occupation_familyback_separatedoctor_-8.0':'Do not know', 
            'SOC_occupation_familyback_separatedoctor_111.0':'111. Chief executives and senior officials',
            'SOC_occupation_familyback_separatedoctor_112.0':'112. Production managers and directors',
            'SOC_occupation_familyback_separatedoctor_113.0':'113. Functional managers and directors',
            'SOC_occupation_familyback_separatedoctor_114.0':'114. Directors in logistics, warehousing and transport',
            'SOC_occupation_familyback_separatedoctor_115.0':'115. Managers and directors in retail and wholesale', 
            'SOC_occupation_familyback_separatedoctor_116.0':'116. Senior officers in protective services',
            'SOC_occupation_familyback_separatedoctor_117.0':'117. Health and social services managers and directors',
            'SOC_occupation_familyback_separatedoctor_121.0':'121. Managers and proprietors in agriculture related services',
            'SOC_occupation_familyback_separatedoctor_122.0':'122. Managers and proprietors in hospitality and leisure services',
            'SOC_occupation_familyback_separatedoctor_123.0':'123. Managers and proprietors in health and care services',
            'SOC_occupation_familyback_separatedoctor_124.0':'124. Managers in logistics, warehousing and transport',
            'SOC_occupation_familyback_separatedoctor_125.0':'125. Managers and proprietors in other services',
            'SOC_occupation_familyback_separatedoctor_211.0':'211. Natural and social science professionals',
            'SOC_occupation_familyback_separatedoctor_212.0':'212. Engineering professionals',
            'SOC_occupation_familyback_separatedoctor_213.0':'213. Information technology professionals',
            'SOC_occupation_familyback_separatedoctor_214.0':'214. Web and multimedia design professionals',
            'SOC_occupation_familyback_separatedoctor_215.0':'215. Conservation and environment professionals',
            'SOC_occupation_familyback_separatedoctor_216.0':'216. Research and development (r&d) and other research professionals',
            'SOC_occupation_familyback_separatedoctor_221.0':'221. Health professionals (excluding Doctors)',
            'SOC_occupation_familyback_separatedoctor_222.0':'222. Therapy professionals',
            'SOC_occupation_familyback_separatedoctor_223.0':'223. Nursing professionals',
            'SOC_occupation_familyback_separatedoctor_224.0':'224. Veterinarians',
            'SOC_occupation_familyback_separatedoctor_225.0':'225. Other health professionals', 
            'SOC_occupation_familyback_separatedoctor_231.0':'231. Teaching professionals',
            'SOC_occupation_familyback_separatedoctor_232.0':'232. Other educational professionals',
            'SOC_occupation_familyback_separatedoctor_241.0':'241. Legal professionals',
            'SOC_occupation_familyback_separatedoctor_242.0':'242. Finance professionals',
            'SOC_occupation_familyback_separatedoctor_243.0':'243. Business, research and administrative professionals', 
            'SOC_occupation_familyback_separatedoctor_244.0':'244. Business and financial project management professionals', 
            'SOC_occupation_familyback_separatedoctor_245.0':'245. Architects, chartered architectural technologists, planning officers, surveyors and construction professionals',
            'SOC_occupation_familyback_separatedoctor_246.0':'246. Welfare professionals',
            'SOC_occupation_familyback_separatedoctor_247.0':'247. Librarians and related professionals',
            'SOC_occupation_familyback_separatedoctor_248.0':'248. Quality and regulatory professionals',
            'SOC_occupation_familyback_separatedoctor_249.0':'249. Media professionals',
            'SOC_occupation_familyback_separatedoctor_311.0':'311. Science, engineering and production technicians',
            'SOC_occupation_familyback_separatedoctor_312.0':'312. Cad, drawing and architectural technicians',
            'SOC_occupation_familyback_separatedoctor_313.0':'313. Information technology technicians', 
            'SOC_occupation_familyback_separatedoctor_321.0':'321. Health associate professionals', 
            'SOC_occupation_familyback_separatedoctor_322.0':'322. Welfare and housing associate professionals', 
            'SOC_occupation_familyback_separatedoctor_323.0':'323. Teaching and childcare associate professionals', 
            'SOC_occupation_familyback_separatedoctor_324.0':'324. Veterinary nurses',
            'SOC_occupation_familyback_separatedoctor_331.0':'331. Protective service occupations',
            'SOC_occupation_familyback_separatedoctor_341.0':'341. Artistic, literary and media occupations',
            'SOC_occupation_familyback_separatedoctor_342.0':'342. Design occupations', 
            'SOC_occupation_familyback_separatedoctor_343.0':'343. Sports and fitness occupations',
            'SOC_occupation_familyback_separatedoctor_351.0':'351. Transport associate professionals',
            'SOC_occupation_familyback_separatedoctor_352.0':'352. Legal associate professionals',
            'SOC_occupation_familyback_separatedoctor_353.0':'353. Finance associate professionals', 
            'SOC_occupation_familyback_separatedoctor_354.0':'354. Business associate professionals', 
            'SOC_occupation_familyback_separatedoctor_355.0':'355. Sales, marketing and related associate professionals', 
            'SOC_occupation_familyback_separatedoctor_356.0':'356. Public services associate professionals', 
            'SOC_occupation_familyback_separatedoctor_357.0':'357. HR, training and other vocational associate guidance professionals', 
            'SOC_occupation_familyback_separatedoctor_358.0':'358. Regulatory associate professionals', 
            'SOC_occupation_familyback_separatedoctor_411.0':'411. Administrative occupations: government and related organisations', 
            'SOC_occupation_familyback_separatedoctor_412.0':'412. Administrative occupations: finance', 
            'SOC_occupation_familyback_separatedoctor_413.0':'413. Administrative occupations: records',
            'SOC_occupation_familyback_separatedoctor_414.0':'414. Administrative occupations: office managers and supervisors',
            'SOC_occupation_familyback_separatedoctor_415.0':'415. Other administrative occupations',
            'SOC_occupation_familyback_separatedoctor_421.0':'421. Secretarial and related occupations',
            'SOC_occupation_familyback_separatedoctor_511.0':'511. Agricultural and related trades',
            'SOC_occupation_familyback_separatedoctor_521.0':'521. Metal forming, welding and related trades',
            'SOC_occupation_familyback_separatedoctor_522.0':'522. Metal machining, fitting and instrument making trades',
            'SOC_occupation_familyback_separatedoctor_523.0':'523. Vehicle trades',
            'SOC_occupation_familyback_separatedoctor_524.0':'524. Electrical and electronic trades',
            'SOC_occupation_familyback_separatedoctor_525.0':'525. Skilled metal, electrical and electronic trades supervisors',
            'SOC_occupation_familyback_separatedoctor_531.0':'531. Construction and building trades',
            'SOC_occupation_familyback_separatedoctor_532.0':'532. Building finishing trades',
            'SOC_occupation_familyback_separatedoctor_533.0':'533. Construction and building trades supervisors',
            'SOC_occupation_familyback_separatedoctor_541.0':'541. Textiles and garments trades',
            'SOC_occupation_familyback_separatedoctor_542.0':'542. Printing trades',
            'SOC_occupation_familyback_separatedoctor_543.0':'543. Food preparation and hospitality trades',
            'SOC_occupation_familyback_separatedoctor_544.0':'544. Other skilled trades',
            'SOC_occupation_familyback_separatedoctor_611.0':'611. Teaching and childcare support occupations',
            'SOC_occupation_familyback_separatedoctor_612.0':'612. Animal care and control services',
            'SOC_occupation_familyback_separatedoctor_613.0':'613. Caring personal services',
            'SOC_occupation_familyback_separatedoctor_621.0':'621. Leisure and travel services',
            'SOC_occupation_familyback_separatedoctor_622.0':'622. Hairdressers and related services', 
            'SOC_occupation_familyback_separatedoctor_623.0':'623. Housekeeping and related services', 
            'SOC_occupation_familyback_separatedoctor_624.0':'624. Cleaning and housekeeping managers and supervisors', 
            'SOC_occupation_familyback_separatedoctor_625.0':'625. Bed and breakfast and guest house owners and proprietors ', 
            'SOC_occupation_familyback_separatedoctor_631.0':'631. Community and civil enforcement occupations',
            'SOC_occupation_familyback_separatedoctor_711.0':'711. Sales assistants and retail cashiers',
            'SOC_occupation_familyback_separatedoctor_712.0':'712. Sales related occupations',
            'SOC_occupation_familyback_separatedoctor_713.0':'713. Shopkeepers and sales supervisors',
            'SOC_occupation_familyback_separatedoctor_721.0':'721. Customer service occupations',
            'SOC_occupation_familyback_separatedoctor_722.0':'722. Customer service supervisors',
            'SOC_occupation_familyback_separatedoctor_811.0':'811. Process operatives',
            'SOC_occupation_familyback_separatedoctor_812.0':'812. Metal working machine operatives', 
            'SOC_occupation_familyback_separatedoctor_813.0':'813. Plant and machine operatives',
            'SOC_occupation_familyback_separatedoctor_814.0':'814. Assemblers and routine operatives',
            'SOC_occupation_familyback_separatedoctor_815.0':'815. Construction operatives',
            'SOC_occupation_familyback_separatedoctor_816.0':'816. Production, factory and assembly supervisors',
            'SOC_occupation_familyback_separatedoctor_821.0':'821. Road transport drivers',
            'SOC_occupation_familyback_separatedoctor_822.0':'822. Mobile machine drivers and operatives',
            'SOC_occupation_familyback_separatedoctor_823.0':'823. Other drivers and transport operatives',
            'SOC_occupation_familyback_separatedoctor_911.0':'911. Elementary agricultural occupations',
            'SOC_occupation_familyback_separatedoctor_912.0':'912. Elementary construction occupations',
            'SOC_occupation_familyback_separatedoctor_913.0':'913. Elementary process plant occupations',
            'SOC_occupation_familyback_separatedoctor_921.0':'921. Elementary administration occupations',
            'SOC_occupation_familyback_separatedoctor_922.0':'922. Elementary cleaning occupations',
            'SOC_occupation_familyback_separatedoctor_923.0':'923. Elementary security occupations',
            'SOC_occupation_familyback_separatedoctor_924.0':'924. Elementary sales occupations',
            'SOC_occupation_familyback_separatedoctor_925.0':'925. Elementary storage occupations',
            'SOC_occupation_familyback_separatedoctor_926.0':'926. Other elementary services occupations',
            'SOC_occupation_familyback_separatedoctor_-9.0':'Does not apply', 
            'SOC_occupation_familyback_separatedoctor_999.0':'999. Uncoded', 
            
            # Socio-economic background
            # DOCTOR AS PART OF WIDER CATEGORY
            # NS-SEC 9-cat       
             'nssec_familybackground_9cat_1.1':'NS-SEC 1.1. Large employers and higher managerial and administrative occupations (reference)',
            'nssec_familybackground_9cat_1.2':'NS-SEC 1.2. Higher professional occupations',
            'nssec_familybackground_9cat_2':'NS-SEC 2. Lower managerial, administrative and professional occupations',
            'nssec_familybackground_9cat_3':'NS-SEC 3. Intermediate occupations',
            'nssec_familybackground_9cat_4':'NS-SEC 4. Small employers and own account workers',
            'nssec_familybackground_9cat_5':'NS-SEC 5. Lower supervisory and technical occupations',
            'nssec_familybackground_9cat_6':'NS-SEC 6. Semi-routine occupations',
            'nssec_familybackground_9cat_7':'NS-SEC 7. Routine occupations',
            'nssec_familybackground_9cat_8':'NS-SEC 8. Never worked and long-term unemployed',
            'nssec_familybackground_9cat_Not living with family':'Not living with family',
            
            # NS-SEC 8-cat
            'nssec_familybackground_8cat_1':'NS-SEC 1 (reference)',
            'nssec_familybackground_8cat_2':'NS-SEC 2',
            'nssec_familybackground_8cat_3':'NS-SEC 3', 
            'nssec_familybackground_8cat_4':'NS-SEC 4',
            'nssec_familybackground_8cat_5':'NS-SEC 5',
            'nssec_familybackground_8cat_6':'NS-SEC 6',
            'nssec_familybackground_8cat_7':'NS-SEC 7',
            'nssec_familybackground_8cat_8':'NS-SEC 8',
            'nssec_familybackground_8cat_Not living with family':'Not living with family',
            
            # NS-SEC 5-cat
            'nssec_familybackground_5cat_1-2':'NS-SEC 1-2 (reference)',
            'nssec_familybackground_5cat_3':'NS-SEC 3',
            'nssec_familybackground_5cat_4':'NS-SEC 4',
            'nssec_familybackground_5cat_5':'NS-SEC 5',
            'nssec_familybackground_5cat_6-7':'NS-SEC 6-7', 
            'nssec_familybackground_5cat_8':'NS-SEC 8',
            'nssec_familybackground_5cat_Not living with family':'Not living with family',
            
            # NS-SEC 4-cat
            'nssec_familybackground_4cat_1-2':'NS-SEC 1-2 (reference)',
            'nssec_familybackground_4cat_3-4':'NS-SEC 3-4',
            'nssec_familybackground_4cat_5-7':'NS-SEC 5-7',
            'nssec_familybackground_4cat_8':'NS-SEC 8',
            'nssec_familybackground_4cat_Not living with family':'Not living with family',
            
            # NS-SEC 3-cat
            'nssec_familybackground_3cat_1-2':'NS-SEC 1-2. Professional backgrounds (reference)',
            'nssec_familybackground_3cat_3-4':'NS-SEC 3-4. Intermediate backgrounds',
            'nssec_familybackground_3cat_5-8':'NS-SEC 5-8. Working class backgrounds',
            
            # DOCTOR AS SEPARATE CATEGORY
            # NS-SEC 9-cat       
             'nssec_familybackground_separatedoctor_9cat_1.1':'NS-SEC 1.1. Large employers and higher managerial and administrative occupations',
            'nssec_familybackground_separatedoctor_9cat_Doctor':'NS-SEC 1.2. Doctor (reference)',
            'nssec_familybackground_separatedoctor_9cat_1.2':'NS-SEC 1.2. All other higher professional occupations',
            'nssec_familybackground_separatedoctor_9cat_2':'NS-SEC 2. Lower managerial, administrative and professional occupations',
            'nssec_familybackground_separatedoctor_9cat_3':'NS-SEC 3. Intermediate occupations',
            'nssec_familybackground_separatedoctor_9cat_4':'NS-SEC 4. Small employers and own account workers',
            'nssec_familybackground_separatedoctor_9cat_5':'NS-SEC 5. Lower supervisory and technical occupations',
            'nssec_familybackground_separatedoctor_9cat_6':'NS-SEC 6. Semi-routine occupations',
            'nssec_familybackground_separatedoctor_9cat_7':'NS-SEC 7. Routine occupations',
            'nssec_familybackground_separatedoctor_9cat_8':'NS-SEC 8. Never worked and long-term unemployed',
            'nssec_familybackground_separatedoctor_9cat_Not living with family':'Not living with family',

            
            # NS-SEC 8-cat
            'nssec_familybackground_separatedoctor_8cat_Doctor':'NS-SEC 1. Doctor (reference)',
            'nssec_familybackground_separatedoctor_8cat_1':'NS-SEC 1. All other',
            'nssec_familybackground_separatedoctor_8cat_2':'NS-SEC 2',
            'nssec_familybackground_separatedoctor_8cat_3':'NS-SEC 3', 
            'nssec_familybackground_separatedoctor_8cat_4':'NS-SEC 4',
            'nssec_familybackground_separatedoctor_8cat_5':'NS-SEC 5',
            'nssec_familybackground_separatedoctor_8cat_6':'NS-SEC 6',
            'nssec_familybackground_separatedoctor_8cat_7':'NS-SEC 7',
            'nssec_familybackground_separatedoctor_8cat_8':'NS-SEC 8',
            'nssec_familybackground_separatedoctor_8cat_Not living with family':'Not living with family',
            
            # NS-SEC 5-cat
            'nssec_familybackground_separatedoctor_5cat_Doctor':'NS-SEC 1-2. Doctor (reference)', 
            'nssec_familybackground_separatedoctor_5cat_1-2':'NS-SEC 1-2. All other',
            'nssec_familybackground_separatedoctor_5cat_3':'NS-SEC 3',
            'nssec_familybackground_separatedoctor_5cat_4':'NS-SEC 4',
            'nssec_familybackground_separatedoctor_5cat_5':'NS-SEC 5',
            'nssec_familybackground_separatedoctor_5cat_6-7':'NS-SEC 6-7', 
            'nssec_familybackground_separatedoctor_5cat_8':'NS-SEC 8',
            'nssec_familybackground_separatedoctor_5cat_Not living with family':'Not living with family',
            
            # NS-SEC 4-cat
            'nssec_familybackground_separatedoctor_4cat_Doctor':'NS-SEC 1-2. Doctor (reference)',
            'nssec_familybackground_separatedoctor_4cat_1-2':'NS-SEC 1-2. All other',
            'nssec_familybackground_separatedoctor_4cat_3-4':'NS-SEC 3-4',
            'nssec_familybackground_separatedoctor_4cat_5-7':'NS-SEC 5-7',
            'nssec_familybackground_separatedoctor_4cat_8':'NS-SEC 8',
            'nssec_familybackground_separatedoctor_4cat_Not living with family':'Not living with family',
            
            # NS-SEC 3-cat
            'nssec_familybackground_separatedoctor_3cat_Doctor':'NS-SEC 1-2. Doctor (reference)', 
            'nssec_familybackground_separatedoctor_3cat_1-2':'NS-SEC 1-2. All other professional backgrounds',
            'nssec_familybackground_separatedoctor_3cat_3-4':'NS-SEC 3-4. Intermediate backgrounds',
            'nssec_familybackground_separatedoctor_3cat_5-8':'NS-SEC 5-8. Working class backgrounds',
            
            # Survey year
            'lfs_year_2014':'2014', 
            'lfs_year_2015':'2015', 
            'lfs_year_2016':'2016', 
            'lfs_year_2017':'2017', 
            'lfs_year_2018':'2018', 
            'lfs_year_2019':'2019',
            'lfs_year_2020':'2020', 
            'lfs_year_2021':'2021', 
            'lfs_year_2022':'2022', 
            'lfs_year_2023':'2023',
            
            }
            

dictionary['var_string_stacked'] = {#
            # Year turned 18 - year_age18_5yrband_agg_doctoronly
            '12: Pre-1970':'Pre-1970',
            '13: 1970-1975':'1970-1974',
            '14: 1975-1980':'1975-1979',
            '15: 1980-1985':'1980-1984', 
            '16: 1985-1990':'1985-1989',
            '17: 1990-1995':'1990-1994',
            '18: 1995-2000':'1995-1999',
            '19: 2000-2005':'2000-2004', 
            '20: 2005-2010':'2005-2009',
            '21: Post-2010':'Post-2010',
            'Overall':'Overall',
            }

dictionary['var_number_stacked'] = {#
            # Year turned 18 - year_age18_5yrband_agg_doctoronly
            '12: Pre-1970':1,
            '13: 1970-1975':2,
            '14: 1975-1980':3,
            '15: 1980-1985':4, 
            '16: 1985-1990':5,
            '17: 1990-1995':6,
            '18: 1995-2000':7,
            '19: 2000-2005':8, 
            '20: 2005-2010':9,
            '21: Post-2010':10,
            'Overall':11.5,
            }

dictionary['var_number'] = {#
            # Year turned 18 - year_age18_5yrband_agg_doctoronly
            'year_age18_5yrband_agg_doctoronly_12: Pre-1970':1,
            'year_age18_5yrband_agg_doctoronly_13: 1970-1975':2,
            'year_age18_5yrband_agg_doctoronly_14: 1975-1980':3,
            'year_age18_5yrband_agg_doctoronly_15: 1980-1985':4, 
            'year_age18_5yrband_agg_doctoronly_16: 1985-1990':5,
            'year_age18_5yrband_agg_doctoronly_17: 1990-1995':6,
            'year_age18_5yrband_agg_doctoronly_18: 1995-2000':7,
            'year_age18_5yrband_agg_doctoronly_19: 2000-2005':8, 
            'year_age18_5yrband_agg_doctoronly_20: 2005-2010':9,
            'year_age18_5yrband_agg_doctoronly_21: Post-2010':10,
            
            # Year turned 18 - year_age18_5yrband_agg_doctorORdegree
            'year_age18_5yrband_agg_doctorORdegree_11: Pre-1965':0, 
            'year_age18_5yrband_agg_doctorORdegree_12: 1965-1970':1,
            'year_age18_5yrband_agg_doctorORdegree_13: 1970-1975':2,
            'year_age18_5yrband_agg_doctorORdegree_14: 1975-1980':3, 
            'year_age18_5yrband_agg_doctorORdegree_15: 1980-1985':4, 
            'year_age18_5yrband_agg_doctorORdegree_16: 1985-1990':5, 
            'year_age18_5yrband_agg_doctorORdegree_17: 1990-1995':6, 
            'year_age18_5yrband_agg_doctorORdegree_18: 1995-2000':7,
            'year_age18_5yrband_agg_doctorORdegree_19: 2000-2005':8,
            'year_age18_5yrband_agg_doctorORdegree_20: 2005-2010':9,
            'year_age18_5yrband_agg_doctorORdegree_21: Post-2010':10,
            
            # Sex - SEX
            'SEX_1':13.5,
            'SEX_2':12.5,
            
            # Country of birth - CRY12
            # 'CRY12_-9':16,
            'CRY12_356':16,
            'CRY12_586':17,
            'CRY12_616':18, 
            'CRY12_372':19,
            'CRY12_921':20, 
            'CRY12_922':21, 
            'CRY12_923':22,
            'CRY12_924':23,
            'CRY12_926':24,
            'CRY12_997':25, 
            
            # Ethnic group - ETHUKEUL
            'ETHUKEUL_-8':27.5,
            'ETHUKEUL_5':28.5,
            'ETHUKEUL_6':29.5,
            'ETHUKEUL_3':30.5,
            'ETHUKEUL_4':31.5, 
            'ETHUKEUL_7':32.5, 
            'ETHUKEUL_8':33.5, 
            'ETHUKEUL_2':34.5,
            'ETHUKEUL_9':35.5,
            'ETHUKEUL_1':36.5,
            
             
            # Individual occupations - SOC_occupation_familyback_separatedoctor
            'SOC_occupation_familyback_separatedoctor_2211.0':42,
            # 'SOC_occupation_familyback_separatedoctor_-8.0':43, 
            'SOC_occupation_familyback_separatedoctor_111.0':44,
            'SOC_occupation_familyback_separatedoctor_112.0':45,
            'SOC_occupation_familyback_separatedoctor_113.0':46,
            'SOC_occupation_familyback_separatedoctor_114.0':47,
            'SOC_occupation_familyback_separatedoctor_115.0':48, 
            'SOC_occupation_familyback_separatedoctor_116.0':49,
            'SOC_occupation_familyback_separatedoctor_117.0':50,
            'SOC_occupation_familyback_separatedoctor_121.0':51,
            'SOC_occupation_familyback_separatedoctor_122.0':52,
            'SOC_occupation_familyback_separatedoctor_123.0':53,
            'SOC_occupation_familyback_separatedoctor_124.0':54,
            'SOC_occupation_familyback_separatedoctor_125.0':55,
            'SOC_occupation_familyback_separatedoctor_211.0':56,
            'SOC_occupation_familyback_separatedoctor_212.0':57,
            'SOC_occupation_familyback_separatedoctor_213.0':58,
            'SOC_occupation_familyback_separatedoctor_214.0':59,
            'SOC_occupation_familyback_separatedoctor_215.0':60,
            'SOC_occupation_familyback_separatedoctor_216.0':61,
            'SOC_occupation_familyback_separatedoctor_221.0':62,
            'SOC_occupation_familyback_separatedoctor_222.0':63,
            'SOC_occupation_familyback_separatedoctor_223.0':64,
            'SOC_occupation_familyback_separatedoctor_224.0':65,
            'SOC_occupation_familyback_separatedoctor_225.0':66, 
            'SOC_occupation_familyback_separatedoctor_231.0':67,
            'SOC_occupation_familyback_separatedoctor_232.0':68,
            'SOC_occupation_familyback_separatedoctor_241.0':69,
            'SOC_occupation_familyback_separatedoctor_242.0':70,
            'SOC_occupation_familyback_separatedoctor_243.0':71, 
            'SOC_occupation_familyback_separatedoctor_244.0':72, 
            'SOC_occupation_familyback_separatedoctor_245.0':73,
            'SOC_occupation_familyback_separatedoctor_246.0':74,
            'SOC_occupation_familyback_separatedoctor_247.0':75,
            'SOC_occupation_familyback_separatedoctor_248.0':76,
            'SOC_occupation_familyback_separatedoctor_249.0':77,
            'SOC_occupation_familyback_separatedoctor_311.0':78,
            'SOC_occupation_familyback_separatedoctor_312.0':79,
            'SOC_occupation_familyback_separatedoctor_313.0':80, 
            'SOC_occupation_familyback_separatedoctor_321.0':81, 
            'SOC_occupation_familyback_separatedoctor_322.0':82, 
            'SOC_occupation_familyback_separatedoctor_323.0':83, 
            'SOC_occupation_familyback_separatedoctor_324.0':84,
            'SOC_occupation_familyback_separatedoctor_331.0':85,
            'SOC_occupation_familyback_separatedoctor_341.0':86,
            'SOC_occupation_familyback_separatedoctor_342.0':87, 
            'SOC_occupation_familyback_separatedoctor_343.0':88,
            'SOC_occupation_familyback_separatedoctor_351.0':89,
            'SOC_occupation_familyback_separatedoctor_352.0':90,
            'SOC_occupation_familyback_separatedoctor_353.0':91, 
            'SOC_occupation_familyback_separatedoctor_354.0':92, 
            'SOC_occupation_familyback_separatedoctor_355.0':93, 
            'SOC_occupation_familyback_separatedoctor_356.0':94, 
            'SOC_occupation_familyback_separatedoctor_357.0':95, 
            'SOC_occupation_familyback_separatedoctor_358.0':96, 
            'SOC_occupation_familyback_separatedoctor_411.0':97, 
            'SOC_occupation_familyback_separatedoctor_412.0':98, 
            'SOC_occupation_familyback_separatedoctor_413.0':99,
            'SOC_occupation_familyback_separatedoctor_414.0':100,
            'SOC_occupation_familyback_separatedoctor_415.0':101,
            'SOC_occupation_familyback_separatedoctor_421.0':102,
            'SOC_occupation_familyback_separatedoctor_511.0':103,
            'SOC_occupation_familyback_separatedoctor_521.0':104,
            'SOC_occupation_familyback_separatedoctor_522.0':105,
            'SOC_occupation_familyback_separatedoctor_523.0':106,
            'SOC_occupation_familyback_separatedoctor_524.0':107,
            'SOC_occupation_familyback_separatedoctor_525.0':108,
            'SOC_occupation_familyback_separatedoctor_531.0':109,
            'SOC_occupation_familyback_separatedoctor_532.0':110,
            'SOC_occupation_familyback_separatedoctor_533.0':111,
            'SOC_occupation_familyback_separatedoctor_541.0':112,
            'SOC_occupation_familyback_separatedoctor_542.0':113,
            'SOC_occupation_familyback_separatedoctor_543.0':114,
            'SOC_occupation_familyback_separatedoctor_544.0':115,
            'SOC_occupation_familyback_separatedoctor_611.0':116,
            'SOC_occupation_familyback_separatedoctor_612.0':117,
            'SOC_occupation_familyback_separatedoctor_613.0':118,
            
            'SOC_occupation_familyback_separatedoctor_621.0':119,
            'SOC_occupation_familyback_separatedoctor_622.0':120, 
            'SOC_occupation_familyback_separatedoctor_623.0':121, 
            'SOC_occupation_familyback_separatedoctor_624.0':122, 
            'SOC_occupation_familyback_separatedoctor_625.0':123, 
            'SOC_occupation_familyback_separatedoctor_631.0':124,
            
            'SOC_occupation_familyback_separatedoctor_711.0':125,
            'SOC_occupation_familyback_separatedoctor_712.0':126,
            'SOC_occupation_familyback_separatedoctor_713.0':127,
            'SOC_occupation_familyback_separatedoctor_721.0':128,
            'SOC_occupation_familyback_separatedoctor_722.0':129,
            'SOC_occupation_familyback_separatedoctor_811.0':130,
            'SOC_occupation_familyback_separatedoctor_812.0':131,
            'SOC_occupation_familyback_separatedoctor_813.0':132,
            'SOC_occupation_familyback_separatedoctor_814.0':133,
            'SOC_occupation_familyback_separatedoctor_815.0':134,
            'SOC_occupation_familyback_separatedoctor_816.0':135,
            'SOC_occupation_familyback_separatedoctor_821.0':136,
            'SOC_occupation_familyback_separatedoctor_822.0':137,
            'SOC_occupation_familyback_separatedoctor_823.0':138,
            'SOC_occupation_familyback_separatedoctor_911.0':139,
            'SOC_occupation_familyback_separatedoctor_912.0':140,
            'SOC_occupation_familyback_separatedoctor_913.0':141,
            'SOC_occupation_familyback_separatedoctor_921.0':142,
            'SOC_occupation_familyback_separatedoctor_922.0':143,
            'SOC_occupation_familyback_separatedoctor_923.0':144,
            'SOC_occupation_familyback_separatedoctor_924.0':145,
            'SOC_occupation_familyback_separatedoctor_925.0':146,
            'SOC_occupation_familyback_separatedoctor_926.0':147,
            'SOC_occupation_familyback_separatedoctor_-9.0':148, 
            
            # Socio-economic background
            # DOCTOR AS PART OF WIDER CATEGORY
            # NS-SEC 9-cat       
            'nssec_familybackground_9cat_1.1':161,
            'nssec_familybackground_9cat_1.2':162,
            'nssec_familybackground_9cat_2':163,
            'nssec_familybackground_9cat_3':164,
            'nssec_familybackground_9cat_4':165,
            'nssec_familybackground_9cat_5':166,
            'nssec_familybackground_9cat_6':167,
            'nssec_familybackground_9cat_7':168,
            'nssec_familybackground_9cat_8':169,
            'nssec_familybackground_9cat_Not living with family':170,
            
            # NS-SEC 3-cat
            'nssec_familybackground_3cat_1-2':172.5,
            'nssec_familybackground_3cat_3-4':173.5,
            'nssec_familybackground_3cat_5-8':174.5,
            
            # DOCTOR AS SEPARATE CATEGORY
            # NS-SEC 9-cat       
            'nssec_familybackground_separatedoctor_9cat_1.1':180,
            'nssec_familybackground_separatedoctor_9cat_Doctor':181,
            'nssec_familybackground_separatedoctor_9cat_1.2':182,
            'nssec_familybackground_separatedoctor_9cat_2':183,
            'nssec_familybackground_separatedoctor_9cat_3':184,
            'nssec_familybackground_separatedoctor_9cat_4':185,
            'nssec_familybackground_separatedoctor_9cat_5':186,
            'nssec_familybackground_separatedoctor_9cat_6':187,
            'nssec_familybackground_separatedoctor_9cat_7':188,
            'nssec_familybackground_separatedoctor_9cat_8':189,
            'nssec_familybackground_separatedoctor_9cat_Not living with family':190,
            
            # NS-SEC 3-cat
            'nssec_familybackground_separatedoctor_3cat_Doctor':192.5, 
            'nssec_familybackground_separatedoctor_3cat_1-2':193.5,
            'nssec_familybackground_separatedoctor_3cat_3-4':194.5,
            'nssec_familybackground_separatedoctor_3cat_5-8':195.5,
                       
            
            # Survey year
            'lfs_year_2014':210, 
            'lfs_year_2015':211, 
            'lfs_year_2016':212, 
            'lfs_year_2017':213, 
            'lfs_year_2018':214, 
            'lfs_year_2019':215,
            'lfs_year_2020':216, 
            'lfs_year_2021':217, 
            'lfs_year_2022':218, 
            'lfs_year_2023':219,
            }

          

